package main

import _ "embed"

// Tray icons: solid-color filled circles (green/amber/red), one per State,
// generated once via a throwaway script (not committed — see the doc
// comment on iconFor) and checked in here as plain .ico binaries embedded
// at build time.
var (
	//go:embed assets/healthy.ico
	iconHealthy []byte

	//go:embed assets/degraded.ico
	iconDegraded []byte

	//go:embed assets/unreachable.ico
	iconUnreachable []byte
)

// iconFor returns the embedded icon bytes for state, ready to pass to
// systray.SetIcon. The three assets/*.ico files were generated by a
// throwaway Go program (drawing a filled circle and wrapping it as a
// minimal PNG-in-ICO container) run once during development and not kept
// in the repo — only their output is.
func iconFor(state State) []byte {
	switch state {
	case StateHealthy:
		return iconHealthy
	case StateDegraded:
		return iconDegraded
	default:
		return iconUnreachable
	}
}
